apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "your-master-node:6443"
networking:
  podSubnet: "192.168.0.0/16"
dns:
  type: CoreDNS
  imageRepository: k8s.gcr.io
  imageTag: "1.8.4"  
apiServer:
  extraArgs:
    service-cluster-ip-range: "10.96.0.0/12"  
controllerManager: {}
scheduler: {}
certificatesDir: "/etc/kubernetes/pki"
etcd:
  local:
    dataDir: "/var/lib/etcd"
apiServerExtraArgs:
  enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota"
imageRepository: k8s.gcr.io
kubeletExtraArgs:
  feature-gates: "RotateKubeletServerCertificate=true"

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "your-master-node:6443"
networking:
  podSubnet: "192.168.0.0/16"
dns:
  type: CoreDNS
  imageRepository: k8s.gcr.io
  imageTag: "1.8.4"
apiServer:
  extraArgs:
    service-cluster-ip-range: "10.96.0.0/12"
controllerManager:
  extraArgs:
    node-cidr-mask-size: "24"  
scheduler:
  extraArgs:
    profiling: "true"  
certificatesDir: "/etc/kubernetes/pki"
etcd:
  local:
    dataDir: "/var/lib/etcd"
apiServerExtraArgs:
  enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota"
imageRepository: k8s.gcr.io
kubeletExtraArgs:
  feature-gates: "RotateKubeletServerCertificate=true"
